#!/bin/bash

# Auto-Connection Test Script
# Story 6.2: Auto-Connection Engine

echo "🧪 Testing Auto-Connection Engine"
echo "=================================="
echo ""

BOARD_ID="f9ded4ca-834f-4254-984c-8eab64ad27ae"
API_URL="http://localhost:3000"

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo "${BLUE}Test 1: Get Connection Suggestions for Board${NC}"
echo "----------------------------------------------"
echo "Endpoint: GET /api/boards/:boardId/connections/suggest"
echo ""

SUGGESTIONS=$(curl -s "${API_URL}/api/boards/${BOARD_ID}/connections/suggest?minConfidence=0.1")
COUNT=$(echo $SUGGESTIONS | jq -r '.count')

echo "${GREEN}✓ Found $COUNT connection suggestions${NC}"
echo ""
echo "$SUGGESTIONS" | jq '.data[] | {
  from: .sourceCard.content[0:35],
  to: .targetCard.content[0:35],
  confidence: .confidence,
  reason: .reason
}'

echo ""
echo "${BLUE}Test 2: Create Auto-Generated Connection${NC}"
echo "----------------------------------------"
echo "Endpoint: POST /api/boards/:boardId/connections"
echo ""

# Get first suggestion
SOURCE_ID=$(echo $SUGGESTIONS | jq -r '.data[0].sourceCardId')
TARGET_ID=$(echo $SUGGESTIONS | jq -r '.data[0].targetCardId')
CONFIDENCE=$(echo $SUGGESTIONS | jq -r '.data[0].confidence')
REASON=$(echo $SUGGESTIONS | jq -r '.data[0].reason')

# Check if connection already exists
EXISTING=$(curl -s "${API_URL}/api/boards/${BOARD_ID}/connections" | jq ".data[] | select(.sourceCardId == \"$SOURCE_ID\" and .targetCardId == \"$TARGET_ID\")")

if [ ! -z "$EXISTING" ]; then
  echo "${YELLOW}⚠ Connection already exists, skipping creation${NC}"
else
  RESULT=$(curl -s -X POST "${API_URL}/api/boards/${BOARD_ID}/connections" \
    -H "Content-Type: application/json" \
    -d "{
      \"sourceCardId\": \"$SOURCE_ID\",
      \"targetCardId\": \"$TARGET_ID\",
      \"confidence\": $CONFIDENCE,
      \"reason\": \"$REASON\",
      \"isAutoGenerated\": true
    }")
  
  echo "${GREEN}✓ Connection created successfully${NC}"
  echo "$RESULT" | jq '{
    id: .data.id,
    confidence: .data.confidence,
    reason: .data.reason,
    isAutoGenerated: .data.isAutoGenerated
  }'
fi

echo ""
echo "${BLUE}Test 3: Get All Connections (with new fields)${NC}"
echo "---------------------------------------------"
echo "Endpoint: GET /api/boards/:boardId/connections"
echo ""

CONNECTIONS=$(curl -s "${API_URL}/api/boards/${BOARD_ID}/connections")
CONN_COUNT=$(echo $CONNECTIONS | jq '.data | length')

echo "${GREEN}✓ Found $CONN_COUNT existing connections${NC}"
echo ""
echo "$CONNECTIONS" | jq '.data[] | {
  id: .id,
  from: .sourceCard.content[0:30],
  to: .targetCard.content[0:30],
  confidence: .confidence,
  reason: .reason,
  isAutoGenerated: .isAutoGenerated
}'

echo ""
echo "${BLUE}Test 4: Get Suggestions for Single Card${NC}"
echo "---------------------------------------"
echo "Endpoint: GET /api/cards/:cardId/connections/suggest"
echo ""

# Get first card
CARD_ID=$(curl -s "${API_URL}/api/notes/board/${BOARD_ID}" | jq -r '.data[0].id')
CARD_CONTENT=$(curl -s "${API_URL}/api/notes/board/${BOARD_ID}" | jq -r '.data[0].content')

echo "Testing card: \"${CARD_CONTENT:0:40}...\""
echo ""

CARD_SUGGESTIONS=$(curl -s "${API_URL}/api/cards/${CARD_ID}/connections/suggest?minConfidence=0.1")
CARD_COUNT=$(echo $CARD_SUGGESTIONS | jq -r '.count')

echo "${GREEN}✓ Found $CARD_COUNT suggestions for this card${NC}"
echo ""
echo "$CARD_SUGGESTIONS" | jq '.data[] | {
  to: .targetCard.content[0:35],
  confidence: .confidence,
  reason: .reason
}'

echo ""
echo "=================================="
echo "${GREEN}✓ All tests completed successfully!${NC}"
echo "=================================="
