/**
 * Connection Model
 * Epic 6, Story 6.1-6.2: Connection Data Model & Auto-Connection
 * 
 * Represents visual connections between notes/cards on a board
 * Enables mind-mapping, relationship visualization, and auto-discovery
 */

import { CreationOptional, InferAttributes, InferCreationAttributes } from 'sequelize';
import { Table, Column, Model, DataType, ForeignKey, BelongsTo } from 'sequelize-typescript';
import Notes from './NOTES';
import Boards from './BOARDS';

@Table({
  tableName: 'CONNECTIONS',
  timestamps: true,
  createdAt: 'CREATEDAT',
  updatedAt: 'UPDATEDAT',
})
export default class Connections extends Model<InferAttributes<Connections>, InferCreationAttributes<Connections>> {
  @Column({
    type: DataType.UUID,
    defaultValue: DataType.UUIDV4,
    primaryKey: true,
    field: 'ID',
  })
  declare id: CreationOptional<string>;

  @ForeignKey(() => Notes)
  @Column({
    type: DataType.UUID,
    allowNull: false,
    field: 'SOURCECARDID',
  })
  declare sourceCardId: string;

  @BelongsTo(() => Notes, { foreignKey: 'SOURCECARDID', onDelete: 'CASCADE' })
  declare sourceCard?: Notes;

  @ForeignKey(() => Notes)
  @Column({
    type: DataType.UUID,
    allowNull: false,
    field: 'TARGETCARDID',
  })
  declare targetCardId: string;

  @BelongsTo(() => Notes, { foreignKey: 'TARGETCARDID', onDelete: 'CASCADE' })
  declare targetCard?: Notes;

  @ForeignKey(() => Boards)
  @Column({
    type: DataType.UUID,
    allowNull: false,
    field: 'BOARDID',
  })
  declare boardId: string;

  @BelongsTo(() => Boards, { foreignKey: 'BOARDID', onDelete: 'CASCADE' })
  declare board?: Boards;

  @Column({
    type: DataType.STRING,
    allowNull: true,
    field: 'LABEL',
  })
  declare label: CreationOptional<string | null>;

  // Story 6.2: Auto-connection fields
  @Column({
    type: DataType.FLOAT,
    allowNull: true,
    field: 'CONFIDENCE',
  })
  declare confidence: CreationOptional<number | null>;

  @Column({
    type: DataType.TEXT,
    allowNull: true,
    field: 'REASON',
  })
  declare reason: CreationOptional<string | null>;

  @Column({
    type: DataType.BOOLEAN,
    allowNull: false,
    defaultValue: false,
    field: 'ISAUTOGENERATED',
  })
  declare isAutoGenerated: CreationOptional<boolean>;

  @Column({
    type: DataType.DATE,
    allowNull: false,
    defaultValue: DataType.NOW,
    field: 'CREATEDAT',
  })
  declare createdAt: CreationOptional<Date>;

  @Column({
    type: DataType.DATE,
    allowNull: false,
    defaultValue: DataType.NOW,
    field: 'UPDATEDAT',
  })
  declare updatedAt: CreationOptional<Date>;
}
