import { describe, it, expect, beforeAll, afterAll, beforeEach } from 'vitest';
import { Sequelize } from 'sequelize-typescript';
import Connections from '../../models/CONNECTIONS';
import Notes from '../../models/NOTES';
import Boards from '../../models/BOARDS';

describe('Connections Model', () => {
  let sequelize: Sequelize;

  beforeAll(async () => {
    // Use in-memory SQLite for testing
    sequelize = new Sequelize({
      dialect: 'sqlite',
      storage: ':memory:',
      models: [Connections, Notes, Boards],
      logging: false,
    });

    await sequelize.sync({ force: true });
  });

  afterAll(async () => {
    await sequelize.close();
  });

  beforeEach(async () => {
    // Clean up tables before each test
    await Connections.destroy({ where: {}, force: true });
    await Notes.destroy({ where: {}, force: true });
    await Boards.destroy({ where: {}, force: true });
  });

  describe('Model Creation', () => {
    it('should create a connection with required fields', async () => {
      // Create test data
      const board = await Boards.create({ name: 'Test Board' });
      const sourceCard = await Notes.create({
        content: 'Source Card',
        positionX: 0,
        positionY: 0,
        boardId: board.id,
      });
      const targetCard = await Notes.create({
        content: 'Target Card',
        positionX: 100,
        positionY: 100,
        boardId: board.id,
      });

      // Create connection
      const connection = await Connections.create({
        sourceCardId: sourceCard.id,
        targetCardId: targetCard.id,
        boardId: board.id,
      });

      expect(connection.id).toBeDefined();
      expect(connection.sourceCardId).toBe(sourceCard.id);
      expect(connection.targetCardId).toBe(targetCard.id);
      expect(connection.boardId).toBe(board.id);
      expect(connection.isAutoGenerated).toBe(false); // default value
      expect(connection.createdAt).toBeInstanceOf(Date);
      expect(connection.updatedAt).toBeInstanceOf(Date);
    });

    it('should create a connection with optional fields', async () => {
      const board = await Boards.create({ name: 'Test Board' });
      const sourceCard = await Notes.create({
        content: 'Source Card',
        positionX: 0,
        positionY: 0,
        boardId: board.id,
      });
      const targetCard = await Notes.create({
        content: 'Target Card',
        positionX: 100,
        positionY: 100,
        boardId: board.id,
      });

      const connection = await Connections.create({
        sourceCardId: sourceCard.id,
        targetCardId: targetCard.id,
        boardId: board.id,
        label: 'related to',
        confidence: 0.85,
        reason: 'Both discuss similar topics',
        isAutoGenerated: true,
      });

      expect(connection.label).toBe('related to');
      expect(connection.confidence).toBe(0.85);
      expect(connection.reason).toBe('Both discuss similar topics');
      expect(connection.isAutoGenerated).toBe(true);
    });

    it('should auto-generate UUID for id', async () => {
      const board = await Boards.create({ name: 'Test Board' });
      const sourceCard = await Notes.create({
        content: 'Source Card',
        positionX: 0,
        positionY: 0,
        boardId: board.id,
      });
      const targetCard = await Notes.create({
        content: 'Target Card',
        positionX: 100,
        positionY: 100,
        boardId: board.id,
      });

      const connection = await Connections.create({
        sourceCardId: sourceCard.id,
        targetCardId: targetCard.id,
        boardId: board.id,
      });

      expect(connection.id).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
    });
  });

  describe('Validations', () => {
    it('should fail to create connection without sourceCardId', async () => {
      const board = await Boards.create({ name: 'Test Board' });
      const targetCard = await Notes.create({
        content: 'Target Card',
        positionX: 0,
        positionY: 0,
        boardId: board.id,
      });

      await expect(
        Connections.create({
          targetCardId: targetCard.id,
          boardId: board.id,
        } as any)
      ).rejects.toThrow();
    });

    it('should fail to create connection without targetCardId', async () => {
      const board = await Boards.create({ name: 'Test Board' });
      const sourceCard = await Notes.create({
        content: 'Source Card',
        positionX: 0,
        positionY: 0,
        boardId: board.id,
      });

      await expect(
        Connections.create({
          sourceCardId: sourceCard.id,
          boardId: board.id,
        } as any)
      ).rejects.toThrow();
    });

    it('should fail to create connection without boardId', async () => {
      const board = await Boards.create({ name: 'Test Board' });
      const sourceCard = await Notes.create({
        content: 'Source Card',
        positionX: 0,
        positionY: 0,
        boardId: board.id,
      });
      const targetCard = await Notes.create({
        content: 'Target Card',
        positionX: 100,
        positionY: 100,
        boardId: board.id,
      });

      await expect(
        Connections.create({
          sourceCardId: sourceCard.id,
          targetCardId: targetCard.id,
        } as any)
      ).rejects.toThrow();
    });
  });

  describe('Relationships', () => {
    it('should have sourceCard relationship', async () => {
      const board = await Boards.create({ name: 'Test Board' });
      const sourceCard = await Notes.create({
        content: 'Source Card',
        positionX: 0,
        positionY: 0,
        boardId: board.id,
      });
      const targetCard = await Notes.create({
        content: 'Target Card',
        positionX: 100,
        positionY: 100,
        boardId: board.id,
      });

      const connection = await Connections.create({
        sourceCardId: sourceCard.id,
        targetCardId: targetCard.id,
        boardId: board.id,
      });

      const foundConnection = await Connections.findByPk(connection.id, {
        include: [{ association: 'sourceCard' }],
      });

      expect(foundConnection?.sourceCard).toBeDefined();
      expect(foundConnection?.sourceCard?.content).toBe('Source Card');
    });

    it('should have targetCard relationship', async () => {
      const board = await Boards.create({ name: 'Test Board' });
      const sourceCard = await Notes.create({
        content: 'Source Card',
        positionX: 0,
        positionY: 0,
        boardId: board.id,
      });
      const targetCard = await Notes.create({
        content: 'Target Card',
        positionX: 100,
        positionY: 100,
        boardId: board.id,
      });

      const connection = await Connections.create({
        sourceCardId: sourceCard.id,
        targetCardId: targetCard.id,
        boardId: board.id,
      });

      const foundConnection = await Connections.findByPk(connection.id, {
        include: [{ association: 'targetCard' }],
      });

      expect(foundConnection?.targetCard).toBeDefined();
      expect(foundConnection?.targetCard?.content).toBe('Target Card');
    });

    it('should have board relationship', async () => {
      const board = await Boards.create({ name: 'Test Board' });
      const sourceCard = await Notes.create({
        content: 'Source Card',
        positionX: 0,
        positionY: 0,
        boardId: board.id,
      });
      const targetCard = await Notes.create({
        content: 'Target Card',
        positionX: 100,
        positionY: 100,
        boardId: board.id,
      });

      const connection = await Connections.create({
        sourceCardId: sourceCard.id,
        targetCardId: targetCard.id,
        boardId: board.id,
      });

      const foundConnection = await Connections.findByPk(connection.id, {
        include: [{ association: 'board' }],
      });

      expect(foundConnection?.board).toBeDefined();
      expect(foundConnection?.board?.name).toBe('Test Board');
    });
  });

  describe('Cascade Delete', () => {
    it('should delete connection when source card is deleted', async () => {
      const board = await Boards.create({ name: 'Test Board' });
      const sourceCard = await Notes.create({
        content: 'Source Card',
        positionX: 0,
        positionY: 0,
        boardId: board.id,
      });
      const targetCard = await Notes.create({
        content: 'Target Card',
        positionX: 100,
        positionY: 100,
        boardId: board.id,
      });

      const connection = await Connections.create({
        sourceCardId: sourceCard.id,
        targetCardId: targetCard.id,
        boardId: board.id,
      });

      await sourceCard.destroy();

      const foundConnection = await Connections.findByPk(connection.id);
      expect(foundConnection).toBeNull();
    });

    it('should delete connection when target card is deleted', async () => {
      const board = await Boards.create({ name: 'Test Board' });
      const sourceCard = await Notes.create({
        content: 'Source Card',
        positionX: 0,
        positionY: 0,
        boardId: board.id,
      });
      const targetCard = await Notes.create({
        content: 'Target Card',
        positionX: 100,
        positionY: 100,
        boardId: board.id,
      });

      const connection = await Connections.create({
        sourceCardId: sourceCard.id,
        targetCardId: targetCard.id,
        boardId: board.id,
      });

      await targetCard.destroy();

      const foundConnection = await Connections.findByPk(connection.id);
      expect(foundConnection).toBeNull();
    });

    it('should delete connections when board is deleted', async () => {
      const board = await Boards.create({ name: 'Test Board' });
      const sourceCard = await Notes.create({
        content: 'Source Card',
        positionX: 0,
        positionY: 0,
        boardId: board.id,
      });
      const targetCard = await Notes.create({
        content: 'Target Card',
        positionX: 100,
        positionY: 100,
        boardId: board.id,
      });

      const connection = await Connections.create({
        sourceCardId: sourceCard.id,
        targetCardId: targetCard.id,
        boardId: board.id,
      });

      await board.destroy();

      const foundConnection = await Connections.findByPk(connection.id);
      expect(foundConnection).toBeNull();
    });
  });

  describe('Default Values', () => {
    it('should default isAutoGenerated to false', async () => {
      const board = await Boards.create({ name: 'Test Board' });
      const sourceCard = await Notes.create({
        content: 'Source Card',
        positionX: 0,
        positionY: 0,
        boardId: board.id,
      });
      const targetCard = await Notes.create({
        content: 'Target Card',
        positionX: 100,
        positionY: 100,
        boardId: board.id,
      });

      const connection = await Connections.create({
        sourceCardId: sourceCard.id,
        targetCardId: targetCard.id,
        boardId: board.id,
      });

      expect(connection.isAutoGenerated).toBe(false);
    });

    it('should allow null for optional fields', async () => {
      const board = await Boards.create({ name: 'Test Board' });
      const sourceCard = await Notes.create({
        content: 'Source Card',
        positionX: 0,
        positionY: 0,
        boardId: board.id,
      });
      const targetCard = await Notes.create({
        content: 'Target Card',
        positionX: 100,
        positionY: 100,
        boardId: board.id,
      });

      const connection = await Connections.create({
        sourceCardId: sourceCard.id,
        targetCardId: targetCard.id,
        boardId: board.id,
        label: null,
        confidence: null,
        reason: null,
      });

      expect(connection.label).toBeNull();
      expect(connection.confidence).toBeNull();
      expect(connection.reason).toBeNull();
    });
  });

  describe('Timestamps', () => {
    it('should auto-set createdAt and updatedAt', async () => {
      const board = await Boards.create({ name: 'Test Board' });
      const sourceCard = await Notes.create({
        content: 'Source Card',
        positionX: 0,
        positionY: 0,
        boardId: board.id,
      });
      const targetCard = await Notes.create({
        content: 'Target Card',
        positionX: 100,
        positionY: 100,
        boardId: board.id,
      });

      const connection = await Connections.create({
        sourceCardId: sourceCard.id,
        targetCardId: targetCard.id,
        boardId: board.id,
      });

      expect(connection.createdAt).toBeInstanceOf(Date);
      expect(connection.updatedAt).toBeInstanceOf(Date);
      expect(connection.createdAt.getTime()).toBeLessThanOrEqual(connection.updatedAt.getTime());
    });

    it('should update updatedAt on modification', async () => {
      const board = await Boards.create({ name: 'Test Board' });
      const sourceCard = await Notes.create({
        content: 'Source Card',
        positionX: 0,
        positionY: 0,
        boardId: board.id,
      });
      const targetCard = await Notes.create({
        content: 'Target Card',
        positionX: 100,
        positionY: 100,
        boardId: board.id,
      });

      const connection = await Connections.create({
        sourceCardId: sourceCard.id,
        targetCardId: targetCard.id,
        boardId: board.id,
      });

      const originalUpdatedAt = connection.updatedAt;

      // Wait a bit to ensure timestamp difference
      await new Promise(resolve => setTimeout(resolve, 10));

      connection.label = 'updated label';
      await connection.save();

      expect(connection.updatedAt.getTime()).toBeGreaterThan(originalUpdatedAt.getTime());
    });
  });
});
