/**
 * Hook: useConnectionSuggestions
 * Story 6.3: Connection Suggestions UI
 * 
 * Manages fetching and interacting with auto-generated connection suggestions
 */

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useCallback, useEffect, useState } from 'react';
import type { ConnectionSuggestion } from '../types/types';

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:3000';

interface CreateConnectionData {
  sourceCardId: string;
  targetCardId: string;
  confidence: number;
  reason: string;
  isAutoGenerated: boolean;
}

/**
 * Fetch connection suggestions for a board
 */
async function fetchConnectionSuggestions(
  boardId: string,
  minConfidence: number = 0.15
): Promise<ConnectionSuggestion[]> {
  const response = await fetch(
    `${API_URL}/api/boards/${boardId}/connections/suggest?minConfidence=${minConfidence}`
  );

  if (!response.ok) {
    throw new Error('Failed to fetch connection suggestions');
  }

  const data = await response.json();
  return data.data;
}

/**
 * Create a connection (accept a suggestion)
 */
async function createConnection(
  boardId: string,
  data: CreateConnectionData
): Promise<any> {
  const response = await fetch(`${API_URL}/api/boards/${boardId}/connections`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(data),
  });

  if (!response.ok) {
    const error = await response.json();
    throw new Error(error.error?.message || 'Failed to create connection');
  }

  return response.json();
}

/**
 * Get/Set rejected suggestions from localStorage
 */
function getRejectedSuggestions(boardId: string): Set<string> {
  try {
    const stored = localStorage.getItem(`rejected-suggestions-${boardId}`);
    return stored ? new Set(JSON.parse(stored)) : new Set();
  } catch {
    return new Set();
  }
}

function saveRejectedSuggestions(boardId: string, rejections: Set<string>) {
  try {
    localStorage.setItem(
      `rejected-suggestions-${boardId}`,
      JSON.stringify([...rejections])
    );
  } catch (error) {
    console.error('Failed to save rejections to localStorage:', error);
  }
}

/**
 * Hook for managing connection suggestions
 */
export function useConnectionSuggestions(boardId: string | null) {
  const queryClient = useQueryClient();
  const [rejectedSuggestions, setRejectedSuggestions] = useState<Set<string>>(new Set());

  // Load rejected suggestions from localStorage when boardId changes
  useEffect(() => {
    if (boardId) {
      setRejectedSuggestions(getRejectedSuggestions(boardId));
    }
  }, [boardId]);

  // Fetch suggestions (lazy - only when enabled)
  const {
    data: suggestions = [],
    isLoading,
    isError,
    error,
    refetch,
  } = useQuery({
    queryKey: ['connection-suggestions', boardId],
    queryFn: () => fetchConnectionSuggestions(boardId!, 0.10), // 10% threshold for better results
    enabled: false, // Lazy - only fetch when explicitly called
    staleTime: 5 * 60 * 1000, // Cache for 5 minutes
  });

  // Accept suggestion mutation
  const acceptMutation = useMutation({
    mutationFn: (suggestion: ConnectionSuggestion) =>
      createConnection(boardId!, {
        sourceCardId: suggestion.sourceCardId,
        targetCardId: suggestion.targetCardId,
        confidence: suggestion.confidence,
        reason: suggestion.reason,
        isAutoGenerated: true,
      }),
    onSuccess: () => {
      // Invalidate connections query to refresh the list
      queryClient.invalidateQueries({ queryKey: ['connections', boardId] });
      // Refetch suggestions to get updated list (backend now filters existing connections)
      refetch();
    },
  });

  // Accept a suggestion
  const acceptSuggestion = async (suggestion: ConnectionSuggestion) => {
    try {
      await acceptMutation.mutateAsync(suggestion);
      return { success: true };
    } catch (error: any) {
      return { success: false, error: error.message };
    }
  };

  // Reject a suggestion (save to localStorage)
  const rejectSuggestion = (suggestion: ConnectionSuggestion) => {
    if (!boardId) return;
    
    const key = `${suggestion.sourceCardId}-${suggestion.targetCardId}`;
    const newRejections = new Set([...rejectedSuggestions, key]);
    setRejectedSuggestions(newRejections);
    saveRejectedSuggestions(boardId, newRejections);
  };

  // Clear all rejections
  const clearRejections = () => {
    if (!boardId) return;
    
    setRejectedSuggestions(new Set());
    localStorage.removeItem(`rejected-suggestions-${boardId}`);
  };

  // Filter out rejected suggestions
  const filteredSuggestions = suggestions.filter((suggestion) => {
    const key = `${suggestion.sourceCardId}-${suggestion.targetCardId}`;
    return !rejectedSuggestions.has(key);
  });

  // Load suggestions (trigger the query) - wrapped in useCallback for stable reference
  const loadSuggestions = useCallback(() => {
    // Don't clear rejections on reload - let user manually clear them
    refetch();
  }, [refetch]);

  return {
    suggestions: filteredSuggestions,
    isLoading,
    isError,
    error,
    loadSuggestions,
    acceptSuggestion,
    rejectSuggestion,
    clearRejections,
    hasRejections: rejectedSuggestions.size > 0,
    isAccepting: acceptMutation.isPending,
  };
}
