/**
 * Hook: useConnections
 * Story 6.4: Draw Connection Lines
 * 
 * Manages fetching and deleting connections for visualization
 */

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { toast } from 'sonner';

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:3000';

export interface Connection {
  id: string;
  sourceCardId: string;
  targetCardId: string;
  boardId: string;
  label?: string | null;
  confidence?: number | null;
  reason?: string | null;
  isAutoGenerated: boolean;
  sourceCard: {
    id: string;
    content: string;
    positionX: string | number;
    positionY: string | number;
    type: 'note' | 'idea' | 'plan';
  };
  targetCard: {
    id: string;
    content: string;
    positionX: string | number;
    positionY: string | number;
    type: 'note' | 'idea' | 'plan';
  };
}

/**
 * Fetch all connections for a board
 */
async function fetchConnections(boardId: string): Promise<Connection[]> {
  const response = await fetch(`${API_URL}/api/boards/${boardId}/connections`);

  if (!response.ok) {
    throw new Error('Failed to fetch connections');
  }

  const data = await response.json();
  
  // Ensure positions are numbers
  return data.data.map((conn: Connection) => ({
    ...conn,
    sourceCard: {
      ...conn.sourceCard,
      positionX: Number(conn.sourceCard.positionX),
      positionY: Number(conn.sourceCard.positionY),
    },
    targetCard: {
      ...conn.targetCard,
      positionX: Number(conn.targetCard.positionX),
      positionY: Number(conn.targetCard.positionY),
    },
  }));
}

/**
 * Delete a connection
 */
async function deleteConnection(connectionId: string): Promise<void> {
  const response = await fetch(`${API_URL}/api/connections/${connectionId}`, {
    method: 'DELETE',
  });

  if (!response.ok) {
    const error = await response.json();
    throw new Error(error.error?.message || 'Failed to delete connection');
  }
}

/**
 * Hook for managing connections
 */
export function useConnections(boardId: string | null) {
  const queryClient = useQueryClient();

  // Fetch connections
  const {
    data: connections = [],
    isLoading,
    isError,
    error,
  } = useQuery({
    queryKey: ['connections', boardId],
    queryFn: () => fetchConnections(boardId!),
    enabled: !!boardId,
    refetchInterval: 1000, // Refetch every 1 second for real-time updates during drag
  });

  // Delete connection mutation
  const deleteMutation = useMutation({
    mutationFn: deleteConnection,
    onSuccess: () => {
      // Invalidate queries to refetch
      queryClient.invalidateQueries({ queryKey: ['connections', boardId] });
      queryClient.invalidateQueries({ queryKey: ['connection-suggestions', boardId] });
      toast.success('Connection deleted');
    },
    onError: (error: Error) => {
      toast.error(`Failed to delete connection: ${error.message}`);
    },
  });

  const deleteConnectionById = (connectionId: string) => {
    deleteMutation.mutate(connectionId);
  };

  return {
    connections,
    isLoading,
    isError,
    error,
    deleteConnection: deleteConnectionById,
    isDeleting: deleteMutation.isPending,
  };
}
