export type Note = {
  id: string;
  title?: string | null;
  content: string;
  type?: 'note' | 'idea' | 'plan';
  status?: 'active' | 'archived' | 'graduated';
  positionX: number;
  positionY: number;
  backgroundColor: string;
  textColor: string;
  boardId?: string | null;
  userId?: string | null;
  archivedAt?: string | null;
  zIndex?: number;
  createdAt?: string;
  updatedAt?: string;
  // Epic 7: resurfacing tracking
  lastViewedAt?: string | null;
  lastResurfacedAt?: string | null;
  resurfaceCount?: number;
  actedOnResurface?: boolean;
};

// Story 3.1: Board type
export type Board = {
  id: string;
  name: string;
  userId?: string | null;
  lastOpenedAt?: string | null;
  createdAt?: string;
  updatedAt?: string;
};

// Story 6.1-6.2: Connection type (with auto-connection support)
export type Connection = {
  id: string;
  sourceCardId: string;
  targetCardId: string;
  boardId: string;
  label?: string | null;
  confidence?: number | null; // Story 6.2: Auto-connection confidence (0.0 - 1.0)
  reason?: string | null; // Story 6.2: Why the connection was suggested
  isAutoGenerated?: boolean; // Story 6.2: Whether this was auto-generated
  sourceCard?: Note;
  targetCard?: Note;
  createdAt?: string;
  updatedAt?: string;
};

// Story 6.2: Connection suggestion (not yet created)
export type ConnectionSuggestion = {
  sourceCardId: string;
  targetCardId: string;
  confidence: number;
  reason: string;
  sourceCard?: Note;
  targetCard?: Note;
};

// Epic 8, Story 8.1: Next Time Note
export type NextTimeNote = {
  id: string;
  parentNoteId: string;
  content: string;
  completedAt?: string | null;
  createdAt?: string;
};

// Epic 8, Story 8.3: Activity Log Entry
export type ActivityEventType =
  | 'created'
  | 'edited'
  | 'type_changed'
  | 'status_changed'
  | 'connected'
  | 'resurfaced'
  | 'next_time_added'
  | 'next_time_completed'
  | 'graduated';

export type ActivityLogEntry = {
  id: string;
  noteId: string;
  eventType: ActivityEventType;
  payload?: Record<string, unknown> | null;
  createdAt: string;
};
