import { describe, it, expect, vi, beforeEach } from 'vitest';
import express from 'express';
import request from 'supertest';
import { connectionRouter } from '../../routes/connection-route';
import * as connectionService from '../../services/connection-service';
import * as autoConnectionService from '../../services/auto-connection-service';

// Mock the database config to prevent Sequelize initialization
vi.mock('../../config/db', () => ({
  sequelize: {
    transaction: vi.fn(async (callback) => {
      const mockTransaction = {
        commit: vi.fn(),
        rollback: vi.fn(),
      };
      if (callback) {
        return await callback(mockTransaction);
      }
      return mockTransaction;
    }),
  },
  connectDB: vi.fn(),
}));

// Mock the services
vi.mock('../../services/connection-service');
vi.mock('../../services/auto-connection-service');

const app = express();
app.use(express.json());
app.use('/api', connectionRouter);

describe('Connection Routes', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  describe('POST /api/boards/:boardId/connections', () => {
    it('should return 201 with { data: connection }', async () => {
      const mockConnection = {
        id: 'conn-123',
        sourceCardId: 'card-1',
        targetCardId: 'card-2',
        boardId: 'board-123',
        label: 'related to',
        confidence: 0.85,
        reason: 'Both discuss similar topics',
        isAutoGenerated: true,
      };

      vi.mocked(connectionService.createConnection).mockResolvedValue(mockConnection as any);

      const response = await request(app)
        .post('/api/boards/board-123/connections')
        .send({
          sourceCardId: 'card-1',
          targetCardId: 'card-2',
          label: 'related to',
          confidence: 0.85,
          reason: 'Both discuss similar topics',
          isAutoGenerated: true,
        });

      expect(response.status).toBe(201);
      expect(response.body).toEqual({ data: mockConnection });
      expect(connectionService.createConnection).toHaveBeenCalledWith(
        expect.objectContaining({
          sourceCardId: 'card-1',
          targetCardId: 'card-2',
          boardId: 'board-123',
        }),
        expect.any(Object)
      );
    });

    it('should return 400 with VALIDATION_ERROR when sourceCardId is missing', async () => {
      const response = await request(app)
        .post('/api/boards/board-123/connections')
        .send({
          targetCardId: 'card-2',
        });

      expect(response.status).toBe(400);
      expect(response.body).toEqual({
        error: { code: 'VALIDATION_ERROR', message: 'Source and target card IDs are required' }
      });
      expect(connectionService.createConnection).not.toHaveBeenCalled();
    });

    it('should return 400 with VALIDATION_ERROR when connecting card to itself', async () => {
      vi.mocked(connectionService.createConnection).mockRejectedValue(
        new Error('Cannot connect a card to itself')
      );

      const response = await request(app)
        .post('/api/boards/board-123/connections')
        .send({
          sourceCardId: 'card-1',
          targetCardId: 'card-1',
        });

      expect(response.status).toBe(400);
      expect(response.body).toEqual({
        error: { code: 'VALIDATION_ERROR', message: 'Cannot connect a card to itself' }
      });
    });

    it('should return 404 with NOT_FOUND when card does not exist', async () => {
      vi.mocked(connectionService.createConnection).mockRejectedValue(
        new Error('One or both cards not found on this board')
      );

      const response = await request(app)
        .post('/api/boards/board-123/connections')
        .send({
          sourceCardId: 'card-1',
          targetCardId: 'fake-card',
        });

      expect(response.status).toBe(404);
      expect(response.body).toEqual({
        error: { code: 'NOT_FOUND', message: 'One or both cards not found on this board' }
      });
    });

    it('should return 409 with CONFLICT when connection already exists', async () => {
      vi.mocked(connectionService.createConnection).mockRejectedValue(
        new Error('Connection already exists')
      );

      const response = await request(app)
        .post('/api/boards/board-123/connections')
        .send({
          sourceCardId: 'card-1',
          targetCardId: 'card-2',
        });

      expect(response.status).toBe(409);
      expect(response.body).toEqual({
        error: { code: 'CONFLICT', message: 'Connection already exists' }
      });
    });
  });

  describe('GET /api/boards/:boardId/connections', () => {
    it('should return 200 with { data: connections[] }', async () => {
      const mockConnections = [
        {
          id: 'conn-1',
          sourceCardId: 'card-1',
          targetCardId: 'card-2',
          boardId: 'board-123',
        },
        {
          id: 'conn-2',
          sourceCardId: 'card-2',
          targetCardId: 'card-3',
          boardId: 'board-123',
        },
      ];

      vi.mocked(connectionService.getConnectionsByBoardId).mockResolvedValue(mockConnections as any);

      const response = await request(app).get('/api/boards/board-123/connections');

      expect(response.status).toBe(200);
      expect(response.body).toEqual({ data: mockConnections });
      expect(connectionService.getConnectionsByBoardId).toHaveBeenCalledWith('board-123');
    });

    it('should return 500 with INTERNAL_ERROR on failure', async () => {
      vi.mocked(connectionService.getConnectionsByBoardId).mockRejectedValue(
        new Error('Database error')
      );

      const response = await request(app).get('/api/boards/board-123/connections');

      expect(response.status).toBe(500);
      expect(response.body).toEqual({
        error: { code: 'INTERNAL_ERROR', message: 'Failed to fetch connections' }
      });
    });
  });

  describe('GET /api/cards/:cardId/connections', () => {
    it('should return 200 with { data: connections[] }', async () => {
      const mockConnections = [
        {
          id: 'conn-1',
          sourceCardId: 'card-1',
          targetCardId: 'card-2',
        },
      ];

      vi.mocked(connectionService.getConnectionsByCardId).mockResolvedValue(mockConnections as any);

      const response = await request(app).get('/api/cards/card-1/connections');

      expect(response.status).toBe(200);
      expect(response.body).toEqual({ data: mockConnections });
      expect(connectionService.getConnectionsByCardId).toHaveBeenCalledWith('card-1');
    });
  });

  describe('DELETE /api/connections/:id', () => {
    it('should return 204 with no content', async () => {
      vi.mocked(connectionService.deleteConnectionById).mockResolvedValue(undefined);

      const response = await request(app).delete('/api/connections/conn-123');

      expect(response.status).toBe(204);
      expect(response.body).toEqual({});
      expect(connectionService.deleteConnectionById).toHaveBeenCalledWith('conn-123', expect.any(Object));
    });

    it('should return 404 with NOT_FOUND when connection does not exist', async () => {
      vi.mocked(connectionService.deleteConnectionById).mockRejectedValue(
        new Error('Connection not found')
      );

      const response = await request(app).delete('/api/connections/fake-id');

      expect(response.status).toBe(404);
      expect(response.body).toEqual({
        error: { code: 'NOT_FOUND', message: 'Connection not found' }
      });
    });
  });

  describe('GET /api/boards/:boardId/connections/suggest', () => {
    it('should return 200 with { data: suggestions[], count }', async () => {
      const mockSuggestions = [
        {
          sourceCard: { id: 'card-1', content: 'Task A' },
          targetCard: { id: 'card-2', content: 'Task B' },
          confidence: 0.85,
          reason: 'Both mention similar keywords',
        },
        {
          sourceCard: { id: 'card-1', content: 'Task A' },
          targetCard: { id: 'card-3', content: 'Task C' },
          confidence: 0.75,
          reason: 'Related topics',
        },
      ];

      vi.mocked(autoConnectionService.suggestConnections).mockResolvedValue(mockSuggestions as any);

      const response = await request(app).get('/api/boards/board-123/connections/suggest');

      expect(response.status).toBe(200);
      expect(response.body).toEqual({
        data: mockSuggestions,
        count: 2,
      });
      expect(autoConnectionService.suggestConnections).toHaveBeenCalledWith('board-123', 0.2, undefined);
    });

    it('should accept minConfidence query parameter', async () => {
      vi.mocked(autoConnectionService.suggestConnections).mockResolvedValue([]);

      const response = await request(app).get('/api/boards/board-123/connections/suggest?minConfidence=0.5');

      expect(response.status).toBe(200);
      expect(autoConnectionService.suggestConnections).toHaveBeenCalledWith('board-123', 0.5, undefined);
    });

    it('should accept useAI=true query parameter', async () => {
      vi.mocked(autoConnectionService.suggestConnections).mockResolvedValue([]);

      const response = await request(app).get('/api/boards/board-123/connections/suggest?useAI=true');

      expect(response.status).toBe(200);
      expect(autoConnectionService.suggestConnections).toHaveBeenCalledWith('board-123', 0.2, true);
    });

    it('should accept useAI=false query parameter', async () => {
      vi.mocked(autoConnectionService.suggestConnections).mockResolvedValue([]);

      const response = await request(app).get('/api/boards/board-123/connections/suggest?useAI=false');

      expect(response.status).toBe(200);
      expect(autoConnectionService.suggestConnections).toHaveBeenCalledWith('board-123', 0.2, false);
    });

    it('should return 500 with INTERNAL_ERROR on failure', async () => {
      vi.mocked(autoConnectionService.suggestConnections).mockRejectedValue(
        new Error('Analysis failed')
      );

      const response = await request(app).get('/api/boards/board-123/connections/suggest');

      expect(response.status).toBe(500);
      expect(response.body).toEqual({
        error: { code: 'INTERNAL_ERROR', message: 'Failed to suggest connections' }
      });
    });
  });

  describe('GET /api/cards/:cardId/connections/suggest', () => {
    it('should return 200 with { data: suggestions[], count }', async () => {
      const mockSuggestions = [
        {
          sourceCard: { id: 'card-1', content: 'Task A' },
          targetCard: { id: 'card-2', content: 'Task B' },
          confidence: 0.85,
          reason: 'Similar content',
        },
      ];

      vi.mocked(autoConnectionService.suggestConnectionsForCard).mockResolvedValue(mockSuggestions as any);

      const response = await request(app).get('/api/cards/card-1/connections/suggest');

      expect(response.status).toBe(200);
      expect(response.body).toEqual({
        data: mockSuggestions,
        count: 1,
      });
      expect(autoConnectionService.suggestConnectionsForCard).toHaveBeenCalledWith('card-1', 0.2);
    });

    it('should return 404 with NOT_FOUND when card does not exist', async () => {
      vi.mocked(autoConnectionService.suggestConnectionsForCard).mockRejectedValue(
        new Error('Card not found')
      );

      const response = await request(app).get('/api/cards/fake-id/connections/suggest');

      expect(response.status).toBe(404);
      expect(response.body).toEqual({
        error: { code: 'NOT_FOUND', message: 'Card not found' }
      });
    });
  });

  describe('Response format compliance', () => {
    it('should use { data } format for successful responses', async () => {
      const mockConnections = [{ id: 'conn-1' }];
      vi.mocked(connectionService.getConnectionsByBoardId).mockResolvedValue(mockConnections as any);

      const response = await request(app).get('/api/boards/board-123/connections');

      expect(response.body).toHaveProperty('data');
      expect(response.body).not.toHaveProperty('result');
      expect(response.body).not.toHaveProperty('success');
    });

    it('should use { error } format for error responses', async () => {
      vi.mocked(connectionService.getConnectionsByBoardId).mockRejectedValue(new Error('DB error'));

      const response = await request(app).get('/api/boards/board-123/connections');

      expect(response.body).toHaveProperty('error');
      expect(response.body.error).toHaveProperty('code');
      expect(response.body.error).toHaveProperty('message');
    });
  });
});
