/**
 * Component: ConnectionLine
 * Story 6.4: Draw Connection Lines
 * 
 * Renders a single connection as a curved SVG line with arrow
 */

import { motion } from 'framer-motion';
import { useState } from 'react';
import type { Connection } from '../../hooks/useConnections';

interface ConnectionLineProps {
  connection: Connection;
  onDelete?: (connectionId: string) => void;
  zoom?: number;
}

/**
 * Get color based on confidence level
 */
function getConnectionColor(confidence: number | null | undefined): string {
  if (!confidence) return '#94a3b8'; // Neutral gray for manual connections
  if (confidence >= 0.3) return '#10b981'; // Green (high confidence)
  if (confidence >= 0.15) return '#f59e0b'; // Yellow (medium confidence)
  return '#3b82f6'; // Blue (low confidence)
}

/**
 * Calculate bezier curve path for smooth connection line
 */
function calculatePath(
  sourceX: number,
  sourceY: number,
  targetX: number,
  targetY: number
): string {
  // Calculate midpoint
  const midX = (sourceX + targetX) / 2;
  const midY = (sourceY + targetY) / 2;

  // Offset control point perpendicular to line for curve
  const dx = targetX - sourceX;
  const dy = targetY - sourceY;
  const distance = Math.sqrt(dx * dx + dy * dy);
  
  // Curve intensity based on distance (longer lines = more curve)
  const curveOffset = Math.min(distance * 0.2, 80);
  
  // Perpendicular vector
  const perpX = -dy / distance;
  const perpY = dx / distance;
  
  const controlX = midX + perpX * curveOffset;
  const controlY = midY + perpY * curveOffset;

  // Quadratic bezier curve
  return `M ${sourceX},${sourceY} Q ${controlX},${controlY} ${targetX},${targetY}`;
}

/**
 * Calculate angle for arrow head (at the end of the curve)
 */
function calculateArrowAngle(
  sourceX: number,
  sourceY: number,
  targetX: number,
  targetY: number
): number {
  // For a curved line, we need the angle at the END, not the start
  // Use the vector from control point to target for better accuracy
  const dx = targetX - sourceX;
  const dy = targetY - sourceY;
  const distance = Math.sqrt(dx * dx + dy * dy);
  const curveOffset = Math.min(distance * 0.2, 80);
  
  const midX = (sourceX + targetX) / 2;
  const midY = (sourceY + targetY) / 2;
  const perpX = -dy / distance;
  const perpY = dx / distance;
  const controlX = midX + perpX * curveOffset;
  const controlY = midY + perpY * curveOffset;
  
  // Angle from control point to target
  const angle = Math.atan2(targetY - controlY, targetX - controlX);
  return (angle * 180) / Math.PI;
}

export function ConnectionLine({ connection, onDelete }: ConnectionLineProps) {
  const [isHovered, setIsHovered] = useState(false);

  // Card dimensions (w-52 = 13rem = 208px, approximate height)
  const cardWidth = 208;
  const cardHeight = 120; // Approximate height for center

  // Calculate line endpoints (center of cards) - ensure numbers
  const sourceX = Number(connection.sourceCard.positionX) + cardWidth / 2;
  const sourceY = Number(connection.sourceCard.positionY) + cardHeight / 2;
  const targetX = Number(connection.targetCard.positionX) + cardWidth / 2;
  const targetY = Number(connection.targetCard.positionY) + cardHeight / 2;

  // Generate path
  const path = calculatePath(sourceX, sourceY, targetX, targetY);
  const arrowAngle = calculateArrowAngle(sourceX, sourceY, targetX, targetY);

  // Color based on confidence
  const color = getConnectionColor(connection.confidence);

  // Line style based on type
  const strokeDasharray = connection.isAutoGenerated ? 'none' : '8,4';

  const handleClick = (e: React.MouseEvent) => {
    e.stopPropagation();
    if (onDelete && window.confirm('Delete this connection?')) {
      onDelete(connection.id);
    }
  };

  return (
    <motion.g
      initial={{ opacity: 0 }}
      animate={{ opacity: isHovered ? 1 : 0.6 }}
      exit={{ opacity: 0 }}
      transition={{ duration: 0.2 }}
      onMouseEnter={() => setIsHovered(true)}
      onMouseLeave={() => setIsHovered(false)}
      onClick={handleClick}
      style={{ cursor: 'pointer' }}
    >
      {/* Invisible thick line for easier clicking */}
      <path
        d={path}
        fill="none"
        stroke="transparent"
        strokeWidth={20}
        strokeLinecap="round"
      />

      {/* Visible line */}
      <motion.path
        d={path}
        fill="none"
        stroke={color}
        strokeWidth={isHovered ? 3 : 2}
        strokeLinecap="round"
        strokeDasharray={strokeDasharray}
        style={{
          filter: isHovered ? 'drop-shadow(0 0 4px rgba(0,0,0,0.3))' : 'none',
        }}
      />

      {/* Arrow head - larger and properly positioned */}
      <motion.polygon
        points="0,-6 15,0 0,6"
        fill={color}
        transform={`translate(${targetX},${targetY}) rotate(${arrowAngle})`}
        style={{
          transformOrigin: '0 0',
        }}
      />

      {/* Tooltip on hover */}
      {isHovered && connection.reason && (
        <g>
          <rect
            x={(sourceX + targetX) / 2 - 100}
            y={(sourceY + targetY) / 2 - 30}
            width={200}
            height={40}
            fill="rgba(0,0,0,0.8)"
            rx={4}
          />
          <text
            x={(sourceX + targetX) / 2}
            y={(sourceY + targetY) / 2 - 10}
            textAnchor="middle"
            fill="white"
            fontSize={12}
            style={{ pointerEvents: 'none' }}
          >
            {connection.reason}
          </text>
          <text
            x={(sourceX + targetX) / 2}
            y={(sourceY + targetY) / 2 + 8}
            textAnchor="middle"
            fill="#94a3b8"
            fontSize={10}
            style={{ pointerEvents: 'none' }}
          >
            Click to delete
          </text>
        </g>
      )}
    </motion.g>
  );
}
